$info = array{
		'firstName' => 'Saptarshi',
		'LastName' => 'Paul',
		'photoURL' =>'profile.jpg',
		'birthday' => strtotime('15-02-1994'),
		'city'	=> 'New York',
		'country' => 'United States',
		'street' => "6942 43rd Ave Woodside",
		'zip' => '11377',
		'company' => 'N/A',
		'email' => 'saptarp@g.clemson.edu',
		'cellphone'=> '919-985-3862',
		'description' => 'I am a passionate software developer with the ability to adapt to any situation. My basics are strong which helps me to pick up ne w technology very fast.",
	'tags' => 'Developer, Designer, Singer, Dancer, Painter',
	'facebook' => 'http://www.facebook.com/',
	'github' => 'http://www.github.com/',
	'linkedIn' =>'http://www.linkedIn.com/',
};
